### ISSUE TITLE
Fix DNS (https & www)

### ISSUE THREAD

**Issue by Clindbergh** [mib-unibe/unihack#122]
We need a forwarding (or domain alias) from: `www.unihack.ch` to `unihack.ch` and from `http` to `https`.

Reason: If users enter the domain with the `www` subdomain - and they do - they won't be able to reach the domain, even after manually fixing the mistake.

This is high priority as sponsors might not be able to reach the page.

**Comment by ioboi** [comment]
It should work.

**Comment by ioboi** [comment]
@DonGiovanni83 @Clindbergh Could you confirm this?

**Comment by Clindbergh** [comment]
`curl` seems to receive the correct header on my machine. I would yet like to try it on another machine that hasn't been on the site so far.
