### ISSUE TITLE
Overlapping Text on mobile

### ISSUE THREAD

**Issue by LukasACH** [mib-unibe/unihack#133]
The title "Sponsors"/"Sponsoren" overlaps with the Logo on both [en](https://unihack.ch/en/sponsors/)/[de](https://unihack.ch/sponsors/) pages

**Comment by ioboi** [comment]
Hi, thank you for opening an issue.
Can you supply a screenshot?

**Comment by LukasACH** [comment]
Like this? https://ibb.co/Qf4kJdw

**Comment by ioboi** [comment]
Thank you very much. We will fix this issue.
