### ISSUE TITLE
We should consider autoprefixing

### ISSUE THREAD

**Issue by Clindbergh** [mib-unibe/unihack#34]
[Hugo supports PostCSS](https://gohugo.io/hugo-pipes/postcss/), but it would require a globally installed npm package. If we enable it, we could use auto prefixing. It would:

* add vendor prefixes to css properties where we might have forgotten those, thus making the page render correctly on all devices
* make our code more precise, since vendor prefixes can be removed

Not sure how compatible this would be with travis.

**Comment by ioboi** [comment]
Closed by #43
